# Generated by Django 5.0.4 on 2024-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='about.jpg', upload_to='images/'),
        ),
    ]
